### ISSUE TITLE
Derivative of spline

### ISSUE THREAD

**Issue by Frederik-Baetens** [hadronized/splines#10]
Is it possible to create an implementation which would allow you to get the derivative of the spline at any point?

**Comment by phaazon** [comment]
That’s an interesting topic! If you feel you want to do it, I’d accept the contribution warmly! Otherwise I can do it but I have lots of stuff to do on my spare time right now. :)

**Comment by Frederik-Baetens** [comment]
Hmm, i'll have a look at it, since it doesn't seem too different from calculating the spline curve itself, but i'm also quite busy at the moment.

**Comment by phaazon** [comment]
I guess one can use linear formulas to compute it quickly. I’ll have a look too if I find enough spare time. Thanks!

**Comment by Frederik-Baetens** [comment]
This also can be done in a way that is more exact, and very similar to the interpolation itself: http://denkovacs.com/2016/02/catmull-rom-spline-derivatives/

Sorry for not helping more, but i'm really busy with uni projects at the moment.

**Comment by phaazon** [comment]
Thanks for pointing out!

**Comment by hadronized** [comment]
I’m moving the project to [sourcehut](https://sr.ht/~hadronized/splines/). Feel free to reopen there if you want to — [issues](https://todo.sr.ht/~hadronized/splines) / [mailing list](https://lists.sr.ht/~hadronized/splines). Thank you.
