### ISSUE TITLE
Support for `Spline`s based on `VecDeque`

### ISSUE THREAD

**Issue by GyulyVGC** [hadronized/splines#105]
Hi guys and thanks for this handy library!

With this issue I'd like to propose supporting `Spline`s based on `VecDeque` instead of just simple `Vec`.

This is particularly helpful in case the first key of the spline object needs to be removed efficiently.
Right now, to do so one must call `remove(0)` that has a O(n) complexity.

**Comment by phaazon** [comment]
Hello!

Yeah, using something more bidirectional is probably a better idea, indeed! I’ll see whenever I have some spare-time to work on that; if anyone else want to make a PR to replace the `Vec` with a `VecDeque`, I’m all good with that.
