### ISSUE TITLE
Doesn't support nalgebra 0.33

### ISSUE THREAD

**Issue by ruhrie** [hadronized/splines#114]
My project builds against nalgebra 0.33 and cargo complains when I build about that Interpolator<f32> isn't implemented for Vector3<f32>. When I looked at the dependencies it links against it lists building splines against nalgebra 0.32.6 since the dependencies list <0.33 in this project. I believe it is currently implementing for the older package and is therefore not implemented on the struct version I am using.

**Comment by hadronized** [comment]
Yes, it would require a bump. Feel free to open a PR!

**Comment by ruhrie** [comment]
Sounds good. Opened a PR with the change [here](https://github.com/hadronized/splines/pull/115). Looks like it literally just needed a bump fortunately.

**Comment by hadronized** [comment]
Thank you. We’ll close that issue when your PR hits a crates.io release — hopefully soon enough this day / tomorrow.

**Comment by hadronized** [comment]
Released with 4.4.0.
