### ISSUE TITLE
Implement the sliding-window spline

### ISSUE THREAD

**Issue by hadronized** [hadronized/splines#16]
Splines, in order to be sampled, need to have their keys sorted by ascending interpolator values. That property allows us to sample in logarithmic time.

However, there is a way to get a sampling in amortized constant time. The idea is simple and will suffice in lots of situations:

  - If you plan to sample points in a single direction (ascending or descending) related to the interpolator value. For instance, if you want to discritize the curve by sampling points along the spline, which is something very common, especially in motion and animation.
  - If you plan to go backwards with the same idea as above.
  - If you don’t mind dropping immutability.
  - If you don’t need or don’t have extreme *random-access* lookups in the spline.

The last point is one of the most important, because with that spline type, you can still perform random accesses, but the worst case will make the spline sample in linear time.

The idea:

  1. Wrap a `Spline<T, V>` in a type (I don’t have idea about its type name yet) and add as extra data the index in the spline we’re currently focusing on.
  2. Provide the same interface for sampling as for `Spline`.
  3. The index is used to perform a first lookup in O(1). That gives us a _base_ interpolator value and an _upper_ interpolator value. If the new lookup interpolator value is less than the base, we just decrement the index. If it’s higher, we increment. Do that in a loop (so extreme cases might _slide along_ the whole spline’s keys -> O(n)) until we’re in between.
  4. We now have the key to interpolate with.

If correctly used — e.g. passing values for which a pair in time would result in a small Δ), such sampling is O(1), because we will either be in between keys, or we will just have to perform an increment / decrement. Also, the cache locality is likely to be way better as the keys are in a `Vec` and we’re just reading elements next to each other, vs. a binary search that might be not very cache friendly if the `Vec` gets big.

![](https://phaazon.net/media/uploads/eyebrows.gif)

**Comment by Frederik-Baetens** [comment]
Can't you interpolate in constant time with splines with uniform key spacing by just calculating which points are relevant depending on the parameter?

For example: the max parameter is 8000, if you wanted to interpolate at parameter 5000.5, you would know which keys you needed from the sorted keys list, right?

Sorry if i'm completely wrong here, i don't know enough about splines :stuck_out_tongue:

**Comment by phaazon** [comment]
It works if keys are uniformly spaced, yes! But this is not an assumption by the crate. :)

**Comment by DefinitelyNotKornflex** [comment]
I think you need not drop immutability, you can just have the method for windowing take and return the starting position of the window, or build some mutable iterator on an immutable spline

**Comment by phaazon** [comment]
Yes, I don’t plan to return immutability. It should be two different APIs.
