### ISSUE TITLE
Edge Cases for CatmullRom

### ISSUE THREAD

**Issue by JP-Ellis** [hadronized/splines#37]
Is it possible to have `CatmullRom` support edge cases?

I realize there's some ambiguity in how this is done, but it would be nice to have similar behavior as other interpolation libraries (such as `scipy`).  Some examples of the boundary condition could be:

- Use a one-sided gradient
- Use a manually specified gradient
- Use a 0 gradient
- Wrap around the boundary

Also, it would be helpful if there was some explicit mention of the fact that `CatmullRom` cannot be used near the boundaries in the documentation.

**Comment by hadronized** [comment]
I’m moving the project to [sourcehut](https://sr.ht/~hadronized/splines/). Feel free to reopen there if you want to — [issues](https://todo.sr.ht/~hadronized/splines) / [mailing list](https://lists.sr.ht/~hadronized/splines). Thank you.
