### ISSUE TITLE
Support for extrapolation

### ISSUE THREAD

**Issue by GRASBOCK** [hadronized/splines#48]
I really wish that there was extrapolation. I cannot use it for sampling data outside bounds. clamping is not an option for me. Even linear extrapolation would be ok

**Comment by phaazon** [comment]
Hello!

Sure, why not! I don’t have that much knowledge on extrapolation, but I would be willing to add the feature to the crate!

**Comment by GRASBOCK** [comment]
Great! A simple extended tangent at the ends would be enough. Or second derivative to match endpoint. Or both as a toggle.
I actually built my own spline crate yesterday because I needed extrapolation.
What do you say if I try to integrate that [makima spline](https://crates.io/crates/makima_spline) into your crate?

**Comment by phaazon** [comment]
I’m not a huge fan of how they seem to be doing extrapolation. I think it would be much more elegant to re-use the first / last polynomial.

**Comment by hadronized** [comment]
I’m moving the project to [sourcehut](https://sr.ht/~hadronized/splines/). Feel free to reopen there if you want to — [issues](https://todo.sr.ht/~hadronized/splines) / [mailing list](https://lists.sr.ht/~hadronized/splines). Thank you.
