### ISSUE TITLE
Missing examples of Bezier interpolation

### ISSUE THREAD

**Issue by BrunoWallner** [hadronized/splines#80]
Hello
I wanted to interpolate a vector of 2D points using Bezier-interpolation, but I could not figure out how to do this after looking in the documentation and the examples.
Could anyone tell me how to do this and put it in the documentation?

**Notes**
* I do not know much about interpolation, "tangents" and math in general
* I use it for spectrum audio visualisation

**Comment by phaazon** [comment]
Hey @BrunoWallner, thanks for opening this PR.

I will have a look at the examples / documentation and will enhance that asap.

**Comment by Sinfaen** [comment]
Something I'm also interested in. To generate a quadratic bezier curve, it sounds like I have to input a start point, an end point, and a tangent (scalar value). I thought that the algorithm needs a control point rather than a tangent.

**Comment by hadronized** [comment]
I’m moving the project to [sourcehut](https://sr.ht/~hadronized/splines/). Feel free to reopen there if you want to — [issues](https://todo.sr.ht/~hadronized/splines) / [mailing list](https://lists.sr.ht/~hadronized/splines). Thank you.
